#! /bin/sh

### AUTOSTART ###

sxhkd &
picom &
xfsettingsd &
feh --bg-scale ~/Pictures/jade-stephens-T-FSAK4Bv9c-unsplash.jpg &
polybar mybar &
dropbox &
battery-monitor &
caffeine &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Alacritty state=floating rectangle=800x450+600+350
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=floating rectangle=600x800+600+100
